version: '2.28.1'
services:
  mongo-db-services:
    image: mongo:5.0.27
    container_name: mongo-db-services
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    #ports:
      #- 27017:27017
    volumes:
      - ./data:/data/db
  mongo-express-services:
    image: mongo-express:1.0.2-18-alpine3.19
    restart: always
    container_name: mongo-express-services
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db-services
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8085:8081
    volumes:
      - ./data:/data/db
    depends_on:
      - mongo-db-services